services:
  - type: web
    name: ai-document-assistant-api
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn core.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SERVER_HOST
        value: 0.0.0.0
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: API_SECRET_KEY
        value: local_sec_token_984712839
      - key: LLM_PROVIDER
        value: groq
      - key: GROQ_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
